### ISSUE TITLE
Separation of concerns for config options

### ISSUE THREAD

**Issue by fredrik-macrobond** [zefoy/angular2-swiper-wrapper#4]
I've studied the code more thoroughly now.

I suggest separating the options that are unique for angular2-swiper-wrapper from the options specific for Swiper, and convert them to @Inputs. That would solve some of the problems with the initialization sequence of the view component's template and the differ. 

Like this:
@Input() showScrollbar: boolean;

and then change the init code to this:

``` javascript
if (this.showScrollbar) {
    options.scrollbar =  element.querySelector('.swiper-scrollbar');
}
```

If we still would like to be able to add custom scrollbars, we can instead do like this:

``` javascript

if (this.showScrollbar) {
            if (options.scrollbar) {
                if (typeof options.scrollbar === 'string') options.scrollbar = element.querySelector(options.scrollbar);
            } else {
                options.scrollbar = element.querySelector('.swiper-scrollbar');
            }
        }

```

It would also make it more clear for anybody using this wrapper which options that are swiper specific.

**Comment by sconix** [comment]
Not sure that I understand what you mean. All options are Swiper specific, there is just the easy way to use the default components by defining scrollbar/buttons to true. So its just easier to be able to set the option to true than provide '.swiper-scrollbar' for instance. Having that easier way does not have any effect on the change detection or anything else. The true value is not used by the Swiper so thats why it can be used to tell the wrapper to use the default elements. If you specify anything else then everything works just like in Swiper. So I fail to see how your suggestion would change anything at all in the initialization process, to me its exactly same with more code and extra options that override Swiper options.

So are you still seeing the initialization problem that you described in the previous comment? If you could describe it bit more I could check why it is happening. Was it that you have horizontal swiper and vertical one inside that which causes the problem?

**Comment by fredrik-macrobond** [comment]
I understand your point of view.

I will get back with a more elaborate answer to your question.

**Comment by sconix** [comment]
Thanks, and if you are still seeing the problem you had just try to describe it a bit more and I will gladly try to find a fix for it.
